service: studentit-roster

provider:
  name: aws
  stage: dev
  runtime: dotnetcore1.0
  region: ap-southeast-2
  memorySize: 256
  timeout: 30
  stackTags:
    Purpose: StudentIT

package:
  artifact: bin/release/netcoreapp1.0/publish/deploy-package.zip

functions:
  summary:
    handler: CsharpHandlers::StudentIT.Roster.Summary.Handler::Hello

   #events:
   #  - schedule: rate(10 minutes)
    environment: ${file(env.yml):${self:custom.stage}}

custom:
  stage: "${opt:stage, self:provider.stage}"
