service: studentit-roster

plugins:
  - serverless-secrets-plugin
  - serverless-dotnet-package

provider:
  name: aws
  stage: dev
  runtime: dotnetcore1.0
  region: ap-southeast-2
  memorySize: 128
  timeout: 60
  stackTags:
    Purpose: StudentIT
    Environment: ${self:custom.stage}

functions:
  summary:
    handler: CsharpHandlers::StudentIT.Roster.Summary.Handler::MakeSummary
    environment: ${file(secrets.${self:custom.stage}.yml)}
    events: ${self:custom.${self:custom.stage}.events}

custom:
  stage: ${opt:stage, self:provider.stage}

  prod:
    events:
      - schedule:
          rate: cron(0 7 ? * THU *)
          enabled: false
  dev:
    events:
      - schedule:
          rate: cron(0 7 ? * THU *)
          enabled: true

  dotnetpackage:
    include:
      - extra/**
    configuration: Release
    framework: netcoreapp1.1
